---
- name: install the Postgresql rpm from a remote repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm
    state: present

- name: install the Postgresql96-server rpm from a remote repo
  yum:
    name: postgresql96-server
    state: present

- name: Init DB
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
  args:
    creates: /var/lib/pgsql/9.6/data/pg_hba.conf
  notify:
    - start postgres